import { z } from 'zod';
import type { Db } from './db.js';

/* ------------------------------------------------------------------------------------------------
 * Mining reporting and proof. The compute worker reports every run of the mining engine as a session (start, periodic progress, stop);
 * each progress report may carry one telemetry sample. Raw samples are kept for a few days and rolled up hourly. Every policy, plan and
 * enable/disable change for mining is written to mining_audit_log with the actor, previous and next state, and a high-risk flag.
 * Nothing here can start mining: it only records what the worker says it did, bounded by what is physically possible.
 * ---------------------------------------------------------------------------------------------- */

const iso = z.string().datetime({ offset: true });
export const SessionReport = z.object({
  sessionId: z.string().uuid(),                 // generated by the worker when the engine starts, so retries and late reports are idempotent
  startedAt: iso,
  stoppedAt: iso.nullish(),
  runtimeSeconds: z.number().min(0).max(8 * 86400),
  averageHashrate: z.number().min(0).max(1e9).nullish(),
  peakHashrate: z.number().min(0).max(1e9).nullish(),
  acceptedShares: z.number().int().min(0).max(1e9).default(0),
  rejectedShares: z.number().int().min(0).max(1e9).default(0),
  stopReason: z.string().max(300).nullish(),
  engineVersion: z.string().max(40).nullish(),
  workerVersion: z.string().max(40).nullish(),
  sample: z.object({
    hashrate: z.number().min(0).max(1e9).nullish(),
    cpuUsagePercent: z.number().min(0).max(100).nullish(),
    cpuTempC: z.number().min(0).max(150).nullish(),
    memoryPercent: z.number().min(0).max(100).nullish(),
    poolConnected: z.boolean().nullish(),
    lastShareAt: iso.nullish(),
  }).nullish(),
});
export type SessionReportT = z.infer<typeof SessionReport>;

export const RAW_RETAIN_DAYS = 3;
export const SILENT_SESSION_MINUTES = 15;
const SKEW_MS = 5 * 60_000;

export type SessionResult = { ok: true; id: number; final: boolean } | { ok: false; status: number; error: string };

/** Records one session report from a device. Bounded: a session cannot start in the future or report more runtime than wall-clock time allows. */
export async function recordSession(db: Db, device: { id: string; orgId: string }, b: SessionReportT, now = new Date()): Promise<SessionResult> {
  const md = (await db.query('SELECT worker_id FROM mining_devices WHERE device_id=$1', [device.id])).rows[0];
  if (!md) return { ok: false, status: 409, error: 'this PC has no mining registration (fetch the compute policy first)' };
  const start = new Date(b.startedAt), stop = b.stoppedAt ? new Date(b.stoppedAt) : null;
  if (start.getTime() > now.getTime() + SKEW_MS) return { ok: false, status: 400, error: 'startedAt is in the future' };
  if (start.getTime() < now.getTime() - 8 * 86_400_000) return { ok: false, status: 400, error: 'startedAt is too old' };
  if (stop && (stop < start || stop.getTime() > now.getTime() + SKEW_MS)) return { ok: false, status: 400, error: 'stoppedAt must be between startedAt and now' };
  const end = stop ?? now;
  const runtime = Math.min(b.runtimeSeconds, Math.max(0, (end.getTime() - start.getTime()) / 1000) + 5);
  const avg = b.averageHashrate ?? null;
  const peak = b.peakHashrate == null && avg == null ? null : Math.max(b.peakHashrate ?? 0, avg ?? 0);
  const reason = stop ? (b.stopReason?.trim() || 'not given by the worker') : null;

  const client = await db.connect();
  try {
    await client.query('BEGIN');
    await client.query(
      `INSERT INTO mining_sessions(device_id, org_id, worker_id, client_session_id, started_at, engine_version, agent_version)
       VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (device_id, client_session_id) DO NOTHING`,
      [device.id, device.orgId, md.worker_id, b.sessionId, start, b.engineVersion ?? null, b.workerVersion ?? null]);
    const cur = (await client.query('SELECT id, closed_by, accepted_shares, rejected_shares FROM mining_sessions WHERE device_id=$1 AND client_session_id=$2 FOR UPDATE', [device.id, b.sessionId])).rows[0];
    if (cur.closed_by === 'worker') { await client.query('COMMIT'); return { ok: true, id: Number(cur.id), final: true }; }   // a stop is final; retries change nothing
    // Share counters are cumulative for the session and only ever go up.
    const accepted = Math.max(cur.accepted_shares, b.acceptedShares), rejected = Math.max(cur.rejected_shares, b.rejectedShares);
    await client.query(
      `UPDATE mining_sessions SET runtime_seconds=GREATEST(COALESCE(runtime_seconds,0), $2), average_hashrate=COALESCE($3, average_hashrate),
              peak_hashrate=CASE WHEN $4::float8 IS NULL THEN peak_hashrate ELSE GREATEST(COALESCE(peak_hashrate,0), $4) END,
              accepted_shares=$5, rejected_shares=$6, stopped_at=$7, stop_reason=$8, closed_by=$9, last_report_at=$10,
              engine_version=COALESCE($11, engine_version), agent_version=COALESCE($12, agent_version)
        WHERE id=$1`,
      [cur.id, runtime, avg, peak, accepted, rejected, stop, reason, stop ? 'worker' : null, now, b.engineVersion ?? null, b.workerVersion ?? null]);
    if (b.sample) {
      const s = b.sample;
      await client.query(
        `INSERT INTO mining_telemetry(device_id, org_id, session_id, at, hashrate, cpu_usage_percent, cpu_temp_c, memory_percent, pool_connected, accepted_shares, rejected_shares, accepted_delta, rejected_delta, last_share_at)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)`,
        [device.id, device.orgId, cur.id, now, s.hashrate ?? null, s.cpuUsagePercent ?? null, s.cpuTempC ?? null, s.memoryPercent ?? null, s.poolConnected ?? null,
          accepted, rejected, accepted - cur.accepted_shares, rejected - cur.rejected_shares, s.lastShareAt ? new Date(s.lastShareAt) : null]);
    }
    await client.query('COMMIT');
    return { ok: true, id: Number(cur.id), final: !!stop };
  } catch (e) { await client.query('ROLLBACK').catch(() => {}); throw e; }
  finally { client.release(); }
}

/** Sessions whose worker went silent (PC off, asleep, worker killed) are closed at their last report. A later worker report may still correct them. */
export async function closeSilentSessions(db: Db, minutes = SILENT_SESSION_MINUTES): Promise<number> {
  const r = await db.query(
    `UPDATE mining_sessions SET stopped_at=last_report_at, closed_by='server',
            stop_reason='no report from the compute worker for ' || $1::int || ' minutes (PC off or asleep, or the worker stopped)'
      WHERE stopped_at IS NULL AND last_report_at < now() - make_interval(mins => $1::int)`, [minutes]);
  return r.rowCount ?? 0;
}

/**
 * Rolls raw samples of every completed hour into mining_telemetry_hourly (recomputed while the raw rows exist, so it is idempotent),
 * then deletes raw samples older than the retention window, whole hours only, after they have been rolled up.
 */
export async function rollupMiningTelemetry(db: Db, retainDays = RAW_RETAIN_DAYS): Promise<{ hours: number; deleted: number }> {
  const client = await db.connect();
  try {
    await client.query('BEGIN');
    const up = await client.query(
      `INSERT INTO mining_telemetry_hourly(device_id, org_id, hour, avg_hashrate, max_hashrate, avg_cpu_percent, max_cpu_temp_c, accepted_shares, rejected_shares, samples)
       SELECT device_id, org_id, date_trunc('hour', at), avg(hashrate), max(hashrate), avg(cpu_usage_percent), max(cpu_temp_c), sum(accepted_delta), sum(rejected_delta), count(*)
         FROM mining_telemetry WHERE at < date_trunc('hour', now()) GROUP BY device_id, org_id, date_trunc('hour', at)
       ON CONFLICT (device_id, hour) DO UPDATE SET avg_hashrate=EXCLUDED.avg_hashrate, max_hashrate=EXCLUDED.max_hashrate, avg_cpu_percent=EXCLUDED.avg_cpu_percent,
         max_cpu_temp_c=EXCLUDED.max_cpu_temp_c, accepted_shares=EXCLUDED.accepted_shares, rejected_shares=EXCLUDED.rejected_shares, samples=EXCLUDED.samples`);
    const del = await client.query(`DELETE FROM mining_telemetry WHERE at < date_trunc('hour', now() - make_interval(days => $1::int))`, [retainDays]);
    await client.query('COMMIT');
    return { hours: up.rowCount ?? 0, deleted: del.rowCount ?? 0 };
  } catch (e) { await client.query('ROLLBACK').catch(() => {}); throw e; }
  finally { client.release(); }
}

export async function miningTick(db: Db) { await closeSilentSessions(db); await rollupMiningTelemetry(db); }

// ---------------- audit ----------------
export interface MiningAuditEntry {
  orgId: string; actorType: 'user' | 'platform' | 'system' | 'device'; actorId?: string | null; actorLabel?: string | null; action: string;
  deviceId?: string | null; previous?: unknown; next?: unknown; agentVersion?: string | null; reasons?: string[];
}
/** high_risk is set exactly when there is at least one reason. */
export async function miningAudit(db: Db, e: MiningAuditEntry) {
  const reasons = e.reasons ?? [];
  const uuidOrNull = (s?: string | null) => s && /^[0-9a-f-]{36}$/i.test(s) ? s : null;
  await db.query(
    `INSERT INTO mining_audit_log(org_id, actor_type, actor_id, actor_label, action, device_id, high_risk, reasons, previous, next, agent_version)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,
    [e.orgId, e.actorType, uuidOrNull(e.actorId), e.actorLabel ?? null, e.action, e.deviceId ?? null, reasons.length > 0, reasons,
      e.previous === undefined ? null : JSON.stringify(e.previous), e.next === undefined ? null : JSON.stringify(e.next), e.agentVersion ?? null]);
}

type Settings = { enabled?: boolean; maxCpuPercent?: number; maxTempC?: number; allowOnBattery?: boolean; maxMemoryPercent?: number; fallback?: string;
  pool?: { endpoints?: { host: string; port: number; tls?: boolean }[]; payoutAddress?: string } | null } | null | undefined;

/** The action name and the high-risk reasons for a compute policy change. A change that makes mining start, pay elsewhere or work harder is high-risk. */
export function classifyPolicyChange(prev: Settings, next: Settings): { action: string; reasons: string[] } {
  const r: string[] = [];
  const was = !!prev?.enabled, is = !!next?.enabled;
  if (!was && is) r.push('compute enabled');
  if ((prev?.pool?.payoutAddress ?? null) !== (next?.pool?.payoutAddress ?? null) && next?.pool?.payoutAddress) r.push(prev?.pool?.payoutAddress ? 'payout address changed' : 'payout address set');
  const ep = (s: Settings) => JSON.stringify((s?.pool?.endpoints ?? []).map(e => [e.host.toLowerCase(), e.port, e.tls !== false]));
  if (ep(prev) !== ep(next) && (next?.pool?.endpoints?.length ?? 0) > 0) r.push('mining pool changed');
  if (next?.fallback === 'xmrig' && prev?.fallback !== 'xmrig') r.push('mining engine selected as the workload');
  if (prev && next && (next.maxCpuPercent ?? 0) > (prev.maxCpuPercent ?? 0)) r.push(`CPU limit raised ${prev.maxCpuPercent}% -> ${next.maxCpuPercent}%`);
  if (prev && next && (next.maxTempC ?? 0) > (prev.maxTempC ?? 0)) r.push(`temperature limit raised ${prev.maxTempC} -> ${next.maxTempC} °C`);
  if (prev && next && (next.maxMemoryPercent ?? 0) > (prev.maxMemoryPercent ?? 0)) r.push(`memory limit raised ${prev.maxMemoryPercent}% -> ${next.maxMemoryPercent}%`);
  if (!prev?.allowOnBattery && next?.allowOnBattery) r.push('allowed on battery');
  const action = !prev ? 'policy.create' : was && !is ? 'policy.disable' : !was && is ? 'policy.enable' : 'policy.update';
  return { action, reasons: r };
}
