using UnityEngine;

namespace Breach.Presentation
{
    /// <summary>
    /// Runtime material factory. Template materials are generated by the
    /// editor build step (BREACH.Editor.MaterialForge) into Resources so the
    /// URP shaders and their variants are guaranteed to be in the player build.
    /// </summary>
    public static class BreachMaterials
    {
        static Material _lit, _litEmissive, _unlit, _unlitTransparent, _particlesAdditive, _particlesAlpha;

        static readonly int BaseColor = Shader.PropertyToID("_BaseColor");
        static readonly int BaseMap = Shader.PropertyToID("_BaseMap");
        static readonly int Smoothness = Shader.PropertyToID("_Smoothness");
        static readonly int Metallic = Shader.PropertyToID("_Metallic");
        static readonly int EmissionColor = Shader.PropertyToID("_EmissionColor");

        static Material Template(ref Material cache, string resource, string shaderFallback)
        {
            if (cache != null) return cache;
            cache = Resources.Load<Material>("Generated/Materials/" + resource);
            if (cache == null)
            {
                var shader = Shader.Find(shaderFallback);
                if (shader == null) shader = Shader.Find("Sprites/Default");
                cache = new Material(shader) { name = resource + " (fallback)" };
                Debug.LogWarning($"[BREACH] Material template {resource} missing; using {shader.name}.");
            }
            return cache;
        }

        public static Material Lit(Color color, float smoothness = 0.3f, float metallic = 0f, Texture2D albedo = null)
        {
            var m = new Material(Template(ref _lit, "BREACH_Lit", "Universal Render Pipeline/Lit"));
            m.SetColor(BaseColor, color);
            m.SetFloat(Smoothness, smoothness);
            m.SetFloat(Metallic, metallic);
            if (albedo != null) m.SetTexture(BaseMap, albedo);
            return m;
        }

        public static Material LitEmissive(Color color, Color emission)
        {
            // Separate template so the _EMISSION variant is guaranteed to be in the build.
            var m = new Material(Template(ref _litEmissive, "BREACH_LitEmissive", "Universal Render Pipeline/Lit"));
            m.SetColor(BaseColor, color);
            m.SetFloat(Smoothness, 0.6f);
            m.SetFloat(Metallic, 0f);
            m.EnableKeyword("_EMISSION");
            m.SetColor(EmissionColor, emission);
            m.globalIlluminationFlags = MaterialGlobalIlluminationFlags.None;
            return m;
        }

        public static Material Unlit(Color color)
        {
            var m = new Material(Template(ref _unlit, "BREACH_Unlit", "Universal Render Pipeline/Unlit"));
            m.SetColor(BaseColor, color);
            return m;
        }

        public static Material UnlitTransparent(Color color, Texture2D tex = null)
        {
            var m = new Material(Template(ref _unlitTransparent, "BREACH_UnlitTransparent", "Universal Render Pipeline/Unlit"));
            m.SetColor(BaseColor, color);
            if (tex != null) m.SetTexture(BaseMap, tex);
            return m;
        }

        public static Material ParticlesAdditive(Texture2D tex)
        {
            var m = new Material(Template(ref _particlesAdditive, "BREACH_ParticlesAdditive", "Universal Render Pipeline/Particles/Unlit"));
            if (tex != null) m.SetTexture(BaseMap, tex);
            return m;
        }

        public static Material ParticlesAlpha(Texture2D tex, Color tint)
        {
            var m = new Material(Template(ref _particlesAlpha, "BREACH_ParticlesAlpha", "Universal Render Pipeline/Particles/Unlit"));
            if (tex != null) m.SetTexture(BaseMap, tex);
            m.SetColor(BaseColor, tint);
            return m;
        }

        public static void SetColor(Material m, Color c) => m.SetColor(BaseColor, c);
    }
}
