using System.Collections.Generic;
using UnityEngine;

namespace Breach.Presentation
{
    public enum Sfx
    {
        RifleShot,
        RifleTail,
        DryFire,
        MagOut,
        MagIn,
        BoltRelease,
        ImpactFlesh,
        ImpactSurface,
        HitConfirm,
        KillConfirm,
        HunterGrowl,
        HunterShriek,
        HunterStep,
        HunterStrike,
        HunterDeath,
        PlayerHurt,
        MatchStart,
        CountdownTick,
        UiSelect,
        BoundaryWarn,
    }

    /// <summary>
    /// Loads BREACH's synthesized sound set (Resources/Audio, generated by
    /// Tools/audio/generate_sfx.py) and plays it with small pitch/volume
    /// variation so repeated shots never sound mechanical.
    /// </summary>
    public sealed class BreachAudio : MonoBehaviour
    {
        static BreachAudio _instance;
        readonly Dictionary<Sfx, AudioClip[]> _clips = new Dictionary<Sfx, AudioClip[]>();
        readonly List<AudioSource> _voices = new List<AudioSource>();
        int _next;
        public float MasterVolume = 1f;

        public static BreachAudio Instance => _instance;

        public static BreachAudio Create(Transform parent)
        {
            var go = new GameObject("BREACH Audio");
            go.transform.SetParent(parent, false);
            _instance = go.AddComponent<BreachAudio>();
            _instance.Load();
            return _instance;
        }

        void Load()
        {
            foreach (Sfx s in System.Enum.GetValues(typeof(Sfx)))
            {
                var list = new List<AudioClip>();
                string baseName = ToFileName(s);
                var single = Resources.Load<AudioClip>("Audio/" + baseName);
                if (single != null) list.Add(single);
                for (int i = 1; i <= 6; i++)
                {
                    var v = Resources.Load<AudioClip>($"Audio/{baseName}_{i}");
                    if (v != null) list.Add(v);
                }
                if (list.Count == 0) Debug.LogWarning($"[BREACH] Missing audio: {baseName}");
                _clips[s] = list.ToArray();
            }

            for (int i = 0; i < 16; i++)
            {
                var src = gameObject.AddComponent<AudioSource>();
                src.playOnAwake = false;
                src.spatialBlend = 0f;
                _voices.Add(src);
            }
        }

        static string ToFileName(Sfx s)
        {
            // RifleShot -> rifle_shot
            var name = s.ToString();
            var sb = new System.Text.StringBuilder();
            for (int i = 0; i < name.Length; i++)
            {
                if (i > 0 && char.IsUpper(name[i])) sb.Append('_');
                sb.Append(char.ToLowerInvariant(name[i]));
            }
            return sb.ToString();
        }

        public AudioClip Clip(Sfx s)
        {
            if (!_clips.TryGetValue(s, out var arr) || arr.Length == 0) return null;
            return arr[Random.Range(0, arr.Length)];
        }

        public void Play2D(Sfx s, float volume = 1f, float pitchJitter = 0.04f)
        {
            var clip = Clip(s);
            if (clip == null) return;
            var src = _voices[_next];
            _next = (_next + 1) % _voices.Count;
            src.pitch = 1f + Random.Range(-pitchJitter, pitchJitter);
            src.PlayOneShot(clip, volume * MasterVolume);
        }

        /// <summary>Configure a positional source (Hunter voice, footsteps) for convincing room presence.</summary>
        public static AudioSource MakeSpatialSource(GameObject host, float minDistance = 0.6f, float maxDistance = 14f)
        {
            var src = host.AddComponent<AudioSource>();
            src.playOnAwake = false;
            src.spatialBlend = 1f;
            src.rolloffMode = AudioRolloffMode.Logarithmic;
            src.minDistance = minDistance;
            src.maxDistance = maxDistance;
            src.dopplerLevel = 0f;
            src.spread = 40f;
            return src;
        }

        public void PlayAt(AudioSource src, Sfx s, float volume = 1f, float pitchJitter = 0.06f)
        {
            var clip = Clip(s);
            if (clip == null || src == null) return;
            src.pitch = 1f + Random.Range(-pitchJitter, pitchJitter);
            src.PlayOneShot(clip, volume * MasterVolume);
        }
    }
}
